### ISSUE TITLE
What about a demo implementation with Backbone routing??

### ISSUE THREAD

**Issue by juristr** [kendo-labs/kendo-backbone#3]
We're currently experimenting in creating mobile apps with JavaScript and PhoneGap. So far we've taken a look at jQuery Mobile, jQMobi and Telerik Kendo-UI.

We really appreciate your UI framework, especially the build-in UI adaption based on the OS the app is running in (big plus). However, when trying to use it together with our JavaScript framework (which in our case is [JavaScriptMVC](http://javascriptmvc.com) but that doesn't matter, the concepts are the same as in Backbone) we have quite some **problems with the routing**, not to say we're nearly unable to construct a proper rich JavaScript app together with KendoUI.

Normally routing works like `index.html#someroute/withparams`, meaning on your page you then have links like

```
<a href="#someroute/withparams">Click me</a>
```

to which the JavaScript app reacts and activates the proper controller or whatever. **The problem** is the build-in Kendo hashchange mechanism automatically executes `GET` request on each hash change trying to fetch views remotely. In a server-side rendering scenario this is just perfect, but most modern JavaScript frontend frameworks (like Backbone etc...) use client-side rendering (with some of the available templating engines).

jQuery Mobile follows a similar approach, however it allows to disable such behavior programmatically (`$.mobile.hashListeningEnabled = false;`). **Is there any way to do this with Kendo?** Or better, **could you provide use with an example of a mobile JavaScript app that uses (Backbone) routing?**

([TodoMVC has a good implementation of a routing example with Backbone](http://todomvc.com/architecture-examples/backbone/))

**Comment by petyosi** [comment]
Hi Juri,

I am afraid that at this point there is no way to detach the Kendo UI Mobile view navigation from the URL hash changes. 

On a side note, I would like to notice that we do not provide customer support/feature requests through github issues. The recommended way to contact us is by submitting customer support tickets, participating in our forums, or (best suited for such case) using our Feedback UserVoice page - http://feedback.kendoui.com/.
